# Generated by Django 4.2.7 on 2025-09-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=15, unique=True)),
                ('emp_name', models.CharField(max_length=70)),
                ('emp_sal', models.FloatField()),
                ('emp_addr', models.CharField(max_length=200)),
            ],
        ),
    ]
