# Generated by Django 4.2.7 on 2025-09-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='emp_id',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
